export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const PASSWORD_HASHER = Symbol('PASSWORD_HASHER');
export const VERIFICATION_TOKEN_SERVICE = Symbol('VERIFICATION_TOKEN_SERVICE');
export const VERIFICATION_WEBHOOK = Symbol('VERIFICATION_WEBHOOK');
