export const REFRESH_TOKEN_REPOSITORY = Symbol('REFRESH_TOKEN_REPOSITORY');
export const TOKEN_SERVICE = Symbol('TOKEN_SERVICE');
export const TOKEN_HASHER = Symbol('TOKEN_HASHER');
export const PASSWORD_HASHER = Symbol('PASSWORD_HASHER');
export const VERIFICATION_TOKEN_SERVICE = Symbol('VERIFICATION_TOKEN_SERVICE');
export const VERIFICATION_WEBHOOK = Symbol('VERIFICATION_WEBHOOK');
export const USER_AUTH_REPOSITORY = Symbol('USER_AUTH_REPOSITORY');
