CREATE TABLE "status" (
  "id" INTEGER GENERATED ALWAYS AS IDENTITY,
  "date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "status" BOOLEAN NOT NULL DEFAULT false,
  
  CONSTRAINT "status_pkey" PRIMARY KEY ("id")
);
