services:
  db:
    image: postgres:16
    container_name: devhub-postgres
    environment:
      POSTGRES_DB: devhub_dev_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5430:5432'
    volumes:
      - devhub_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d devhub_dev_db']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  devhub_postgres_data:
